// SPDX-FileCopyrightText: © 2025 Claudio Cicconetti <c.cicconetti@iit.cnr.it>
// SPDX-License-Identifier: MIT

#[derive(Debug, PartialEq)]
pub enum LinkType {
    OneOrbitOrbit,
    OneOrbitGround,
    TwoOrbitOrbit,
    TwoOrbitGround,
    TwoGroundGround,
}

pub trait FidelityComputer {
    /// Return the initial fidelity of the EPR pairs generated by the given
    /// transmitter towards the two nodes specified. Return error if `tx` does not
    /// have a transmitter or there is no edge between `tx` and `u` or `v`.
    ///
    /// Parameters:
    /// - `tx`: the node that generates EPR pairs
    /// - `u`: one of the nodes that receives one photon of the EPR pairs
    /// - `v`: the other one
    fn fidelity(
        &self,
        topology: &super::PhysicalTopology,
        tx: u32,
        u: u32,
        v: u32,
    ) -> anyhow::Result<f64>;

    /// Check if the configuration is valid.
    fn valid(&self) -> anyhow::Result<()>;
}

/// Return error if the nodes are not found in the physical topology or there
/// are other argument inconsistencies.
pub fn topology_checks(
    topology: &super::PhysicalTopology,
    tx: u32,
    u: u32,
    v: u32,
) -> anyhow::Result<()> {
    topology.node_valid(tx)?;
    topology.node_valid(u)?;
    topology.node_valid(v)?;
    let tx = petgraph::graph::NodeIndex::from(tx);
    let u = petgraph::graph::NodeIndex::from(u);
    let v = petgraph::graph::NodeIndex::from(v);
    anyhow::ensure!(
        topology.graph.node_weight(tx).unwrap().transmitters > 0,
        "there are no transmitters on board of {}",
        tx.index()
    );
    anyhow::ensure!(
        u != v,
        "rx nodes are the same: {} = {}",
        u.index(),
        v.index()
    );
    anyhow::ensure!(
        matches!(
            topology.graph.node_weight(tx).unwrap().node_type,
            super::NodeType::SAT
        ),
        "node is an OGS and cannot be a transmitter: {}",
        tx.index()
    );

    Ok(())
}

pub fn link_type(
    topology: &super::PhysicalTopology,
    tx: u32,
    u: u32,
    v: u32,
) -> anyhow::Result<LinkType> {
    let tx = petgraph::graph::NodeIndex::from(tx);
    let u = petgraph::graph::NodeIndex::from(u);
    let v = petgraph::graph::NodeIndex::from(v);

    if tx == u {
        anyhow::ensure!(
            topology.graph.find_edge(tx, v).is_some(),
            "there is no edge between nodes {} and {}",
            tx.index(),
            v.index()
        );
        match topology.graph.node_weight(v).unwrap().node_type {
            super::NodeType::SAT => Ok(LinkType::OneOrbitOrbit),
            super::NodeType::OGS => Ok(LinkType::OneOrbitGround),
        }
    } else if tx == v {
        anyhow::ensure!(
            topology.graph.find_edge(tx, u).is_some(),
            "there is no edge between nodes {} and {}",
            tx.index(),
            u.index()
        );
        match topology.graph.node_weight(u).unwrap().node_type {
            super::NodeType::SAT => Ok(LinkType::OneOrbitOrbit),
            super::NodeType::OGS => Ok(LinkType::OneOrbitGround),
        }
    } else {
        anyhow::ensure!(
            topology.graph.find_edge(tx, u).is_some(),
            "there is no edge between nodes {} and {}",
            tx.index(),
            u.index()
        );
        anyhow::ensure!(
            topology.graph.find_edge(tx, v).is_some(),
            "there is no edge between nodes {} and {}",
            tx.index(),
            v.index()
        );
        match topology.graph.node_weight(u).unwrap().node_type {
            super::NodeType::SAT => match topology.graph.node_weight(v).unwrap().node_type {
                super::NodeType::SAT => Ok(LinkType::TwoOrbitOrbit),
                super::NodeType::OGS => Ok(LinkType::TwoOrbitGround),
            },
            super::NodeType::OGS => match topology.graph.node_weight(v).unwrap().node_type {
                super::NodeType::SAT => Ok(LinkType::TwoOrbitGround),
                super::NodeType::OGS => Ok(LinkType::TwoGroundGround),
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::physical_topology::{NodeType, PhysicalTopology};

    #[test]
    fn test_fidelity_computer_functions() {
        let mut topo = PhysicalTopology::from_distances(vec![
            (0, 1, 1.0),
            (0, 2, 1.0),
            (0, 3, 1.0),
            (0, 4, 1.0),
            (4, 5, 1.0),
        ]);

        topo.graph.node_weight_mut(0.into()).unwrap().node_type = NodeType::SAT;
        topo.graph.node_weight_mut(1.into()).unwrap().node_type = NodeType::OGS;
        topo.graph.node_weight_mut(2.into()).unwrap().node_type = NodeType::OGS;
        topo.graph.node_weight_mut(3.into()).unwrap().node_type = NodeType::SAT;
        topo.graph.node_weight_mut(4.into()).unwrap().node_type = NodeType::SAT;
        topo.graph.node_weight_mut(5.into()).unwrap().node_type = NodeType::SAT;

        assert_eq!(LinkType::OneOrbitOrbit, link_type(&topo, 0, 0, 3).unwrap());
        assert_eq!(LinkType::OneOrbitOrbit, link_type(&topo, 0, 3, 0).unwrap());
        assert_eq!(LinkType::OneOrbitGround, link_type(&topo, 0, 0, 1).unwrap());
        assert_eq!(LinkType::OneOrbitGround, link_type(&topo, 0, 1, 0).unwrap());
        assert_eq!(LinkType::TwoOrbitOrbit, link_type(&topo, 0, 3, 4).unwrap());
        assert_eq!(LinkType::TwoOrbitGround, link_type(&topo, 0, 1, 3).unwrap());
        assert_eq!(
            LinkType::TwoGroundGround,
            link_type(&topo, 0, 1, 2).unwrap()
        );

        assert!(link_type(&topo, 0, 0, 5).is_err());
        assert!(link_type(&topo, 0, 5, 0).is_err());
        assert!(link_type(&topo, 0, 1, 5).is_err());
        assert!(link_type(&topo, 0, 0, 0).is_err());

        assert!(topology_checks(&topo, 0, 1, 1).is_err());
        assert!(topology_checks(&topo, 0, 99, 1).is_err());
        assert!(topology_checks(&topo, 99, 1, 2).is_err());
    }
}
