// SPDX-FileCopyrightText: © 2025 Claudio Cicconetti <c.cicconetti@iit.cnr.it>
// SPDX-License-Identifier: MIT

pub trait FidelityComputer {
    /// Return the initial fidelity of the EPR pairs generated by the given
    /// transmitter towards the two nodes specified. Return error if `tx` does not
    /// have a transmitter or there is no edge between `tx` and `u` or `v`.
    ///
    /// Parameters:
    /// - `tx`: the node that generates EPR pairs
    /// - `u`: one of the nodes that receives one photon of the EPR pairs
    /// - `v`: the other one
    fn fidelity(
        &self,
        topology: &super::PhysicalTopology,
        tx: u32,
        u: u32,
        v: u32,
    ) -> anyhow::Result<f64>;

    /// Check if the configuration is valid.
    fn valid(&self) -> anyhow::Result<()>;
}
